#!/usr/bin/env bash
# cfcname - Cloudflare CNAME timed switch manager
# Version: 1.1
# Author: generated by ChatGPT
# License: MIT-friendly, no hardcoded secrets

set -o pipefail

APP_NAME="cfcname"
APP_VERSION="1.1"
CONFIG_DIR="/etc/${APP_NAME}"
CONFIG_FILE="${CONFIG_DIR}/config.json"
BIN_FILE="/usr/local/bin/${APP_NAME}"
STATE_DIR="/var/lib/${APP_NAME}"
BACKUP_DIR="${STATE_DIR}/backups"
LOG_DIR="/var/log/${APP_NAME}"
LOG_FILE="${LOG_DIR}/${APP_NAME}.log"
SYSTEMD_SERVICE="/etc/systemd/system/${APP_NAME}.service"
SYSTEMD_TIMER="/etc/systemd/system/${APP_NAME}.timer"
CRON_FILE="/etc/cron.d/${APP_NAME}"
API_BASE="https://api.cloudflare.com/client/v4"

C_RESET='\033[0m'
C_BLUE='\033[1;34m'
C_CYAN='\033[1;36m'
C_GREEN='\033[1;32m'
C_YELLOW='\033[1;33m'
C_RED='\033[1;31m'
C_GRAY='\033[0;37m'

is_tty() { [[ -t 1 ]]; }
cecho() {
  local color="$1"; shift
  if is_tty; then printf "%b%s%b\n" "$color" "$*" "$C_RESET"; else printf "%s\n" "$*"; fi
}
line() { cecho "$C_CYAN" "────────────────────────────────────────────────────────────"; }

need_root() {
  if [[ "$(id -u)" -ne 0 ]]; then
    cecho "$C_RED" "[ERROR] 请使用 root 运行：sudo $0 $*"
    exit 1
  fi
}

log_msg() {
  local level="$1"; shift
  local msg="$*"
  mkdir -p "$LOG_DIR" 2>/dev/null || true
  local ts
  ts="$(date '+%Y-%m-%d %H:%M:%S %z')"
  printf '[%s] [%s] %s\n' "$ts" "$level" "$msg" >> "$LOG_FILE" 2>/dev/null || true
}

say_info() { cecho "$C_GREEN" "[OK] $*"; log_msg "INFO" "$*"; }
say_warn() { cecho "$C_YELLOW" "[WARN] $*"; log_msg "WARN" "$*"; }
say_error() { cecho "$C_RED" "[ERROR] $*"; log_msg "ERROR" "$*"; }

pause() { read -r -p "按 Enter 返回..." _; }

confirm() {
  local prompt="$1"
  local ans
  read -r -p "${prompt} [y/N]: " ans
  [[ "$ans" == "y" || "$ans" == "Y" || "$ans" == "yes" || "$ans" == "YES" ]]
}

read_required() {
  local prompt="$1"
  local var=""
  while [[ -z "$var" ]]; do
    read -r -p "$prompt" var
    var="$(echo "$var" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
  done
  printf '%s' "$var"
}

read_default() {
  local prompt="$1"
  local default="$2"
  local var
  read -r -p "${prompt} [${default}]: " var
  var="$(echo "$var" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
  [[ -z "$var" ]] && var="$default"
  printf '%s' "$var"
}

read_secret_required() {
  local prompt="$1"
  local var=""
  while [[ -z "$var" ]]; do
    read -r -s -p "$prompt" var
    echo
    var="$(echo "$var" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
  done
  printf '%s' "$var"
}

validate_time() {
  [[ "$1" =~ ^([01][0-9]|2[0-3]):[0-5][0-9]$ ]]
}

sanitize_id() {
  local raw="$1"
  echo "$raw" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]/-/g;s/--*/-/g;s/^-//;s/-$//' | cut -c1-48
}

now_id() { date '+%Y%m%d%H%M%S'; }

ensure_dirs() {
  mkdir -p "$CONFIG_DIR" "$STATE_DIR" "$BACKUP_DIR" "$LOG_DIR"
  chmod 700 "$CONFIG_DIR" "$STATE_DIR" "$BACKUP_DIR" "$LOG_DIR" 2>/dev/null || true
}

detect_pkg_manager() {
  if command -v apt-get >/dev/null 2>&1; then echo apt
  elif command -v dnf >/dev/null 2>&1; then echo dnf
  elif command -v yum >/dev/null 2>&1; then echo yum
  elif command -v apk >/dev/null 2>&1; then echo apk
  else echo unknown
  fi
}

install_deps() {
  local missing=()
  command -v curl >/dev/null 2>&1 || missing+=(curl)
  command -v jq >/dev/null 2>&1 || missing+=(jq)
  command -v flock >/dev/null 2>&1 || missing+=(util-linux)

  if [[ ${#missing[@]} -eq 0 ]]; then
    say_info "依赖已满足：curl jq flock"
    return 0
  fi

  local pm
  pm="$(detect_pkg_manager)"
  say_warn "缺少依赖：${missing[*]}，准备自动安装。"
  case "$pm" in
    apt)
      apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -y curl jq util-linux ca-certificates cron
      ;;
    dnf)
      dnf install -y curl jq util-linux ca-certificates cronie
      ;;
    yum)
      yum install -y curl jq util-linux ca-certificates cronie
      ;;
    apk)
      apk add --no-cache curl jq util-linux ca-certificates dcron
      ;;
    *)
      say_error "无法识别包管理器，请手动安装 curl、jq、flock/util-linux 后重试。"
      return 1
      ;;
  esac
}

init_empty_config() {
  ensure_dirs
  if [[ ! -f "$CONFIG_FILE" ]]; then
    umask 077
    jq -n \
      --arg version "$APP_VERSION" \
      --arg log_file "$LOG_FILE" \
      '{app:"cfcname", version:$version, settings:{backup_keep:60, default_ttl:1, default_proxied:false, log_file:$log_file}, profiles:[], tasks:[]}' > "$CONFIG_FILE"
    chmod 600 "$CONFIG_FILE"
    say_info "已创建空配置：$CONFIG_FILE"
  fi
}

require_config() {
  if [[ ! -f "$CONFIG_FILE" ]]; then
    init_empty_config
  fi
  if ! jq -e '.app == "cfcname"' "$CONFIG_FILE" >/dev/null 2>&1; then
    say_error "配置文件格式异常：$CONFIG_FILE"
    return 1
  fi
}

save_json() {
  local tmp
  tmp="$(mktemp)"
  cat > "$tmp"
  if jq empty "$tmp" >/dev/null 2>&1; then
    cp -a "$CONFIG_FILE" "${BACKUP_DIR}/config_$(date '+%Y%m%d_%H%M%S').json.bak" 2>/dev/null || true
    mv "$tmp" "$CONFIG_FILE"
    chmod 600 "$CONFIG_FILE"
  else
    rm -f "$tmp"
    say_error "生成的新配置不是合法 JSON，已放弃写入。"
    return 1
  fi
}

json_get_profile() {
  local profile_id="$1"
  jq -c --arg id "$profile_id" '.profiles[]? | select(.id == $id)' "$CONFIG_FILE"
}

json_get_task() {
  local task_id="$1"
  jq -c --arg id "$task_id" '.tasks[]? | select(.id == $id)' "$CONFIG_FILE"
}

mask_token() {
  local token="$1"
  local len=${#token}
  if [[ $len -le 10 ]]; then echo "***"; else echo "${token:0:6}...${token: -4}"; fi
}

cf_api() {
  local token="$1"
  local method="$2"
  local endpoint="$3"
  local data="${4:-}"
  local tmp http_code body
  tmp="$(mktemp)"

  if [[ -n "$data" ]]; then
    http_code="$(curl -sS -o "$tmp" -w '%{http_code}' -X "$method" "${API_BASE}${endpoint}" \
      -H "Authorization: Bearer ${token}" \
      -H "Content-Type: application/json" \
      --data "$data")"
  else
    http_code="$(curl -sS -o "$tmp" -w '%{http_code}' -X "$method" "${API_BASE}${endpoint}" \
      -H "Authorization: Bearer ${token}" \
      -H "Content-Type: application/json")"
  fi
  local curl_rc=$?
  body="$(cat "$tmp")"
  rm -f "$tmp"

  if [[ $curl_rc -ne 0 ]]; then
    say_error "curl 请求失败：${method} ${endpoint}"
    return 1
  fi
  if [[ ! "$http_code" =~ ^2 ]]; then
    say_error "Cloudflare API HTTP ${http_code}：${method} ${endpoint}"
    echo "$body" | jq -r '.errors[]?.message // empty' 2>/dev/null | while read -r e; do [[ -n "$e" ]] && say_error "API错误：$e"; done
    return 1
  fi
  if ! echo "$body" | jq -e '.success == true' >/dev/null 2>&1; then
    say_error "Cloudflare API success=false：${method} ${endpoint}"
    echo "$body" | jq -r '.errors[]?.message // empty' 2>/dev/null | while read -r e; do [[ -n "$e" ]] && say_error "API错误：$e"; done
    return 1
  fi
  echo "$body"
}

urlencode() { jq -rn --arg v "$1" '$v|@uri'; }

profile_field() {
  local profile_json="$1"
  local field="$2"
  echo "$profile_json" | jq -r ".$field"
}

fqdn_record_name() {
  local zone="$1"
  local name="$2"
  name="$(echo "$name" | sed 's/[.]$//')"
  zone="$(echo "$zone" | sed 's/[.]$//')"
  if [[ "$name" == "@" || "$name" == "$zone" ]]; then
    echo "$zone"
  elif [[ "$name" == *".${zone}" ]]; then
    echo "$name"
  else
    echo "${name}.${zone}"
  fi
}

list_records_by_name() {
  local profile_json="$1"
  local name="$2"
  local token zone_id encoded
  token="$(profile_field "$profile_json" api_token)"
  zone_id="$(profile_field "$profile_json" zone_id)"
  encoded="$(urlencode "$name")"
  cf_api "$token" GET "/zones/${zone_id}/dns_records?name=${encoded}&per_page=100"
}

test_profile_api() {
  local profile_json="$1"
  local token zone_id
  token="$(profile_field "$profile_json" api_token)"
  zone_id="$(profile_field "$profile_json" zone_id)"
  cf_api "$token" GET "/zones/${zone_id}/dns_records?per_page=1" >/dev/null
}

add_profile_interactive() {
  require_config || return 1
  line
  cecho "$C_BLUE" "新增 Cloudflare 域名配置"
  line
  echo "建议使用 API Token，不建议使用全局 Key；Token 至少需要该 Zone 的 DNS Read + DNS Write。"
  local zone_name zone_id token name id exists profile_json
  zone_name="$(read_required '域名，例如 vkvkvk.vip: ')"
  zone_id="$(read_required 'Cloudflare Zone ID: ')"
  token="$(read_secret_required 'Cloudflare API Token，输入时不回显: ')"
  name="$(read_default '配置名称' "$zone_name")"
  id="$(sanitize_id "$name")"
  [[ -z "$id" ]] && id="profile-$(now_id)"

  exists="$(jq -r --arg id "$id" '.profiles[]? | select(.id == $id) | .id' "$CONFIG_FILE")"
  if [[ -n "$exists" ]]; then
    id="${id}-$(now_id)"
  fi

  profile_json="$(jq -n --arg id "$id" --arg name "$name" --arg zone_name "$zone_name" --arg zone_id "$zone_id" --arg api_token "$token" '{id:$id,name:$name,zone_name:$zone_name,zone_id:$zone_id,api_token:$api_token}')"
  if confirm "是否先进行只读 API 连通性测试"; then
    if ! test_profile_api "$profile_json"; then
      say_error "API 测试失败。请检查 Zone ID、Token 权限、网络连通性。"
      if ! confirm "仍然保存这个配置"; then return 1; fi
    else
      say_info "API 测试通过。"
    fi
  fi

  jq --argjson p "$profile_json" '.profiles += [$p]' "$CONFIG_FILE" | save_json
  say_info "已保存配置：${name}，ID=${id}，Token=$(mask_token "$token")"
}

select_profile_id() {
  require_config || return 1
  local count idx pid
  count="$(jq '.profiles | length' "$CONFIG_FILE")"
  if [[ "$count" -eq 0 ]]; then
    say_warn "当前没有域名配置，请先新增。" >&2
    return 1
  fi
  line >&2
  cecho "$C_BLUE" "请选择域名配置" >&2
  jq -r '.profiles | to_entries[] | "\(.key+1)) \(.value.name)  zone=\(.value.zone_name)  id=\(.value.id)"' "$CONFIG_FILE" >&2
  line >&2
  read -r -p "输入序号: " idx
  if ! [[ "$idx" =~ ^[0-9]+$ ]]; then say_error "序号无效" >&2; return 1; fi
  pid="$(jq -r --argjson i "$((idx-1))" '.profiles[$i].id // empty' "$CONFIG_FILE")"
  [[ -z "$pid" ]] && { say_error "序号不存在" >&2; return 1; }
  echo "$pid"
}

list_profiles() {
  require_config || return 1
  line
  cecho "$C_BLUE" "Cloudflare 域名配置"
  line
  if [[ "$(jq '.profiles | length' "$CONFIG_FILE")" -eq 0 ]]; then
    echo "暂无配置。"
  else
    jq -r '.profiles[] | "ID: \(.id)\n名称: \(.name)\n域名: \(.zone_name)\nZone ID: \(.zone_id)\nToken: " + (.api_token[0:6] + "..." + .api_token[-4:]) + "\n"' "$CONFIG_FILE"
  fi
}

edit_profile_interactive() {
  local pid profile name zone_name zone_id token
  pid="$(select_profile_id)" || return 1
  profile="$(json_get_profile "$pid")"
  name="$(echo "$profile" | jq -r '.name')"
  zone_name="$(echo "$profile" | jq -r '.zone_name')"
  zone_id="$(echo "$profile" | jq -r '.zone_id')"

  line
  cecho "$C_BLUE" "修改域名配置：$name"
  line
  name="$(read_default '配置名称' "$name")"
  zone_name="$(read_default '域名' "$zone_name")"
  zone_id="$(read_default 'Zone ID' "$zone_id")"
  if confirm "是否更新 API Token"; then
    token="$(read_secret_required '新的 API Token，输入时不回显: ')"
    jq --arg id "$pid" --arg name "$name" --arg zone_name "$zone_name" --arg zone_id "$zone_id" --arg token "$token" \
      '(.profiles[] | select(.id == $id)) |= (.name=$name | .zone_name=$zone_name | .zone_id=$zone_id | .api_token=$token)' "$CONFIG_FILE" | save_json
  else
    jq --arg id "$pid" --arg name "$name" --arg zone_name "$zone_name" --arg zone_id "$zone_id" \
      '(.profiles[] | select(.id == $id)) |= (.name=$name | .zone_name=$zone_name | .zone_id=$zone_id)' "$CONFIG_FILE" | save_json
  fi
  say_info "已修改域名配置。"
}

delete_profile_interactive() {
  local pid used
  pid="$(select_profile_id)" || return 1
  used="$(jq -r --arg id "$pid" '[.tasks[]? | select(.profile_id == $id)] | length' "$CONFIG_FILE")"
  if [[ "$used" -gt 0 ]]; then
    say_error "该配置仍被 ${used} 个任务使用，请先删除或修改相关任务。"
    return 1
  fi
  if confirm "确认删除域名配置 ${pid}"; then
    jq --arg id "$pid" '.profiles = [.profiles[] | select(.id != $id)]' "$CONFIG_FILE" | save_json
    say_info "已删除。"
  fi
}

profiles_menu() {
  while true; do
    clear
    line
    cecho "$C_CYAN" "${APP_NAME} v${APP_VERSION}  域名/API 配置管理"
    line
    echo "1) 查看域名配置"
    echo "2) 新增域名配置"
    echo "3) 修改域名配置"
    echo "4) 删除域名配置"
    echo "5) 测试域名配置 API 权限"
    echo "0) 返回主菜单"
    line
    read -r -p "请选择: " c
    case "$c" in
      1) list_profiles; pause ;;
      2) add_profile_interactive; pause ;;
      3) edit_profile_interactive; pause ;;
      4) delete_profile_interactive; pause ;;
      5) local pid p; pid="$(select_profile_id)" && p="$(json_get_profile "$pid")" && test_profile_api "$p" && say_info "API 测试通过。"; pause ;;
      0) return ;;
      *) say_warn "无效选项"; pause ;;
    esac
  done
}

schedule_records_interactive_json() {
  local arr='[]'
  while true; do
    local name target item
    name="$(read_required '  CNAME 名称，例如 x001 或 x001.example.com，输入 done 结束: ')"
    [[ "$name" == "done" || "$name" == "DONE" ]] && break
    target="$(read_required '  CNAME 目标，例如 target.example.com: ')"
    target="$(echo "$target" | sed 's/[.]$//')"
    item="$(jq -n --arg name "$name" --arg target "$target" '{name:$name,target:$target}')"
    arr="$(echo "$arr" | jq --argjson item "$item" '. += [$item]')"
  done
  echo "$arr"
}

add_task_interactive() {
  require_config || return 1
  local pid pname task_name task_id timezone auto_create ttl proxied schedules s_time records sched schedule_count
  pid="$(select_profile_id)" || return 1
  pname="$(json_get_profile "$pid" | jq -r '.name')"
  line
  cecho "$C_BLUE" "新增 CNAME 定时切换任务"
  line
  echo "当前域名配置：$pname"
  task_name="$(read_required '任务名称，例如 vkvkvk-night-switch: ')"
  task_id="$(sanitize_id "$task_name")"
  [[ -z "$task_id" ]] && task_id="task-$(now_id)"
  if [[ -n "$(jq -r --arg id "$task_id" '.tasks[]? | select(.id == $id) | .id' "$CONFIG_FILE")" ]]; then
    task_id="${task_id}-$(now_id)"
  fi
  timezone="$(read_default '时区' 'Asia/Shanghai')"
  auto_create="true"
  confirm "记录不存在时自动创建 CNAME" && auto_create="true" || auto_create="false"
  ttl="$(read_default '新建记录 TTL，1 表示 Cloudflare 自动 TTL' '1')"
  [[ "$ttl" =~ ^[0-9]+$ ]] || ttl="1"
  proxied="false"
  confirm "新建记录是否开启 Cloudflare 代理 proxied=true？多数纯 CNAME 切换建议 DNS only" && proxied="true" || proxied="false"

  schedules='[]'
  schedule_count=0
  while true; do
    while true; do
      s_time="$(read_required '切换时间 HH:MM，例如 21:00: ')"
      validate_time "$s_time" && break
      say_error "时间格式错误，必须是 HH:MM，例如 02:00 或 21:00。"
    done
    echo "请添加这个时间点要指向的 CNAME 映射，输入 done 结束该时间点。"
    records="$(schedule_records_interactive_json)"
    if [[ "$(echo "$records" | jq 'length')" -eq 0 ]]; then
      say_warn "该时间点没有记录，已跳过。"
    else
      sched="$(jq -n --arg time "$s_time" --argjson records "$records" '{time:$time,records:$records}')"
      schedules="$(echo "$schedules" | jq --argjson s "$sched" '. += [$s] | sort_by(.time)')"
      schedule_count=$((schedule_count+1))
    fi
    confirm "是否继续添加另一个切换时间" || break
  done

  if [[ "$schedule_count" -eq 0 ]]; then
    say_error "任务至少需要一个切换时间。"
    return 1
  fi

  jq --arg id "$task_id" --arg name "$task_name" --arg profile_id "$pid" --arg timezone "$timezone" \
     --argjson auto_create "$auto_create" --argjson ttl "$ttl" --argjson proxied "$proxied" --argjson schedules "$schedules" \
     '.tasks += [{id:$id,name:$name,enabled:true,profile_id:$profile_id,timezone:$timezone,auto_create:$auto_create,ttl:$ttl,proxied:$proxied,schedules:$schedules}]' "$CONFIG_FILE" | save_json
  say_info "已新增任务：$task_name，ID=$task_id"
}

quick_init_wizard() {
  clear
  line
  cecho "$C_CYAN" "${APP_NAME} 快速初始化向导"
  line
  echo "这个向导会完成：域名配置 → 多个 CNAME → 多个时间点切换 → 启用定时器。"
  echo "不会在脚本里写死任何域名或 Token，敏感信息只保存到本机 ${CONFIG_FILE}。"
  line
  require_config || return 1
  add_profile_interactive || return 1
  add_task_interactive || return 1
  install_scheduler
  if confirm "是否立即按当前时间窗口执行一次同步"; then
    run_all_tasks force
  fi
  say_info "快速初始化完成。以后输入 cfcname 即可管理。"
}

select_task_id() {
  require_config || return 1
  local count idx tid
  count="$(jq '.tasks | length' "$CONFIG_FILE")"
  if [[ "$count" -eq 0 ]]; then
    say_warn "当前没有任务。" >&2
    return 1
  fi
  line >&2
  cecho "$C_BLUE" "请选择任务" >&2
  jq -r '.tasks | to_entries[] | "\(.key+1)) [" + (if .value.enabled then "启用" else "停用" end) + "] \(.value.name)  id=\(.value.id)"' "$CONFIG_FILE" >&2
  line >&2
  read -r -p "输入序号: " idx
  if ! [[ "$idx" =~ ^[0-9]+$ ]]; then say_error "序号无效" >&2; return 1; fi
  tid="$(jq -r --argjson i "$((idx-1))" '.tasks[$i].id // empty' "$CONFIG_FILE")"
  [[ -z "$tid" ]] && { say_error "序号不存在" >&2; return 1; }
  echo "$tid"
}

list_tasks() {
  require_config || return 1
  line
  cecho "$C_BLUE" "CNAME 定时切换任务"
  line
  if [[ "$(jq '.tasks | length' "$CONFIG_FILE")" -eq 0 ]]; then
    echo "暂无任务。"
    return 0
  fi
  jq -r '
    .tasks[] as $t |
    "ID: \($t.id)\n名称: \($t.name)\n状态: " + (if $t.enabled then "启用" else "停用" end) + "\n域名配置ID: \($t.profile_id)\n时区: \($t.timezone // "Asia/Shanghai")\n自动创建: \($t.auto_create // true)\nTTL: \($t.ttl // 1)  proxied: \($t.proxied // false)\n时间表:\n" +
    (($t.schedules // []) | map("  - \(.time): " + ((.records // []) | map("\(.name)->\(.target)") | join(", "))) | join("\n")) + "\n"
  ' "$CONFIG_FILE"
}

edit_task_basic() {
  local tid task name timezone enabled auto_create ttl proxied
  tid="$(select_task_id)" || return 1
  task="$(json_get_task "$tid")"
  name="$(echo "$task" | jq -r '.name')"
  timezone="$(echo "$task" | jq -r '.timezone // "Asia/Shanghai"')"
  enabled="$(echo "$task" | jq -r '.enabled')"
  auto_create="$(echo "$task" | jq -r '.auto_create // true')"
  ttl="$(echo "$task" | jq -r '.ttl // 1')"
  proxied="$(echo "$task" | jq -r '.proxied // false')"

  name="$(read_default '任务名称' "$name")"
  timezone="$(read_default '时区' "$timezone")"
  ttl="$(read_default '新建记录 TTL' "$ttl")"
  [[ "$ttl" =~ ^[0-9]+$ ]] || ttl=1
  confirm "启用任务" && enabled=true || enabled=false
  confirm "记录不存在时自动创建" && auto_create=true || auto_create=false
  confirm "新建记录 proxied=true" && proxied=true || proxied=false

  jq --arg id "$tid" --arg name "$name" --arg timezone "$timezone" \
     --argjson enabled "$enabled" --argjson auto_create "$auto_create" --argjson ttl "$ttl" --argjson proxied "$proxied" \
     '(.tasks[] | select(.id == $id)) |= (.name=$name | .timezone=$timezone | .enabled=$enabled | .auto_create=$auto_create | .ttl=$ttl | .proxied=$proxied)' "$CONFIG_FILE" | save_json
  say_info "已修改任务基础配置。"
}

add_schedule_to_task() {
  local tid s_time records sched
  tid="$(select_task_id)" || return 1
  while true; do
    s_time="$(read_required '新增切换时间 HH:MM: ')"
    validate_time "$s_time" && break
    say_error "时间格式错误。"
  done
  records="$(schedule_records_interactive_json)"
  [[ "$(echo "$records" | jq 'length')" -eq 0 ]] && { say_error "没有添加任何记录。"; return 1; }
  sched="$(jq -n --arg time "$s_time" --argjson records "$records" '{time:$time,records:$records}')"
  jq --arg id "$tid" --argjson sched "$sched" '(.tasks[] | select(.id == $id).schedules) += [$sched] | (.tasks[] | select(.id == $id).schedules) |= sort_by(.time)' "$CONFIG_FILE" | save_json
  rm -f "${STATE_DIR}/${tid}.state" 2>/dev/null || true
  say_info "已新增时间点。"
}

edit_schedule_records() {
  local tid task idx sidx schedule_count s_time records sched
  tid="$(select_task_id)" || return 1
  task="$(json_get_task "$tid")"
  schedule_count="$(echo "$task" | jq '.schedules | length')"
  [[ "$schedule_count" -eq 0 ]] && { say_error "任务没有时间表。"; return 1; }
  echo "$task" | jq -r '.schedules | to_entries[] | "\(.key+1)) \(.value.time): " + ((.value.records // []) | map("\(.name)->\(.target)") | join(", "))'
  read -r -p "选择要重写的时间点序号: " idx
  [[ "$idx" =~ ^[0-9]+$ ]] || { say_error "序号无效"; return 1; }
  sidx=$((idx-1))
  [[ "$sidx" -ge 0 && "$sidx" -lt "$schedule_count" ]] || { say_error "序号不存在"; return 1; }
  s_time="$(echo "$task" | jq -r --argjson i "$sidx" '.schedules[$i].time')"
  s_time="$(read_default '切换时间 HH:MM' "$s_time")"
  validate_time "$s_time" || { say_error "时间格式错误。"; return 1; }
  echo "请重新添加该时间点的全部 CNAME 映射，输入 done 结束。"
  records="$(schedule_records_interactive_json)"
  [[ "$(echo "$records" | jq 'length')" -eq 0 ]] && { say_error "没有添加任何记录。"; return 1; }
  sched="$(jq -n --arg time "$s_time" --argjson records "$records" '{time:$time,records:$records}')"
  jq --arg id "$tid" --argjson i "$sidx" --argjson sched "$sched" '(.tasks[] | select(.id == $id).schedules[$i]) = $sched | (.tasks[] | select(.id == $id).schedules) |= sort_by(.time)' "$CONFIG_FILE" | save_json
  rm -f "${STATE_DIR}/${tid}.state" 2>/dev/null || true
  say_info "已重写该时间点。"
}

delete_schedule_from_task() {
  local tid task idx sidx schedule_count
  tid="$(select_task_id)" || return 1
  task="$(json_get_task "$tid")"
  schedule_count="$(echo "$task" | jq '.schedules | length')"
  [[ "$schedule_count" -eq 0 ]] && { say_error "任务没有时间表。"; return 1; }
  echo "$task" | jq -r '.schedules | to_entries[] | "\(.key+1)) \(.value.time): " + ((.value.records // []) | map("\(.name)->\(.target)") | join(", "))'
  read -r -p "选择要删除的时间点序号: " idx
  [[ "$idx" =~ ^[0-9]+$ ]] || { say_error "序号无效"; return 1; }
  sidx=$((idx-1))
  [[ "$sidx" -ge 0 && "$sidx" -lt "$schedule_count" ]] || { say_error "序号不存在"; return 1; }
  if confirm "确认删除该时间点"; then
    jq --arg id "$tid" --argjson i "$sidx" '(.tasks[] | select(.id == $id).schedules) |= del(.[$i])' "$CONFIG_FILE" | save_json
    rm -f "${STATE_DIR}/${tid}.state" 2>/dev/null || true
    say_info "已删除时间点。"
  fi
}

toggle_task() {
  local tid enabled new
  tid="$(select_task_id)" || return 1
  enabled="$(json_get_task "$tid" | jq -r '.enabled')"
  if [[ "$enabled" == "true" ]]; then new=false; else new=true; fi
  jq --arg id "$tid" --argjson new "$new" '(.tasks[] | select(.id == $id).enabled) = $new' "$CONFIG_FILE" | save_json
  rm -f "${STATE_DIR}/${tid}.state" 2>/dev/null || true
  say_info "任务状态已切换为：$new"
}

delete_task() {
  local tid
  tid="$(select_task_id)" || return 1
  if confirm "确认删除任务 ${tid}"; then
    jq --arg id "$tid" '.tasks = [.tasks[] | select(.id != $id)]' "$CONFIG_FILE" | save_json
    rm -f "${STATE_DIR}/${tid}.state" 2>/dev/null || true
    say_info "已删除任务。"
  fi
}

tasks_menu() {
  while true; do
    clear
    line
    cecho "$C_CYAN" "${APP_NAME} v${APP_VERSION}  CNAME 任务管理"
    line
    echo "1) 查看任务"
    echo "2) 新增任务"
    echo "3) 修改任务基础配置"
    echo "4) 新增切换时间点"
    echo "5) 修改某个时间点的 CNAME 映射"
    echo "6) 删除某个时间点"
    echo "7) 启用/停用任务"
    echo "8) 删除任务"
    echo "0) 返回主菜单"
    line
    read -r -p "请选择: " c
    case "$c" in
      1) list_tasks; pause ;;
      2) add_task_interactive; pause ;;
      3) edit_task_basic; pause ;;
      4) add_schedule_to_task; pause ;;
      5) edit_schedule_records; pause ;;
      6) delete_schedule_from_task; pause ;;
      7) toggle_task; pause ;;
      8) delete_task; pause ;;
      0) return ;;
      *) say_warn "无效选项"; pause ;;
    esac
  done
}

schedule_key_for_now() {
  local task_json="$1"
  local tz nowhm
  tz="$(echo "$task_json" | jq -r '.timezone // "Asia/Shanghai"')"
  nowhm="$(TZ="$tz" date '+%H%M')"
  echo "$task_json" | jq -c --arg nowhm "$nowhm" '
    (.schedules // []) as $s |
    if ($s|length) == 0 then empty else
      ($s | map(. + {hm:(.time|gsub(":";"")|tonumber)}) | sort_by(.hm)) as $sorted |
      (($sorted | map(select(.hm <= ($nowhm|tonumber))) | last) // ($sorted | last))
    end'
}

desired_hash() {
  local sched_json="$1"
  echo "$sched_json" | jq -c '{time,records}' | sha256sum | awk '{print $1}'
}

backup_records_before_apply() {
  local task_id="$1"
  local profile_json="$2"
  local names_json="$3"
  local backup_file tmp name resp records
  backup_file="${BACKUP_DIR}/dns_${task_id}_$(date '+%Y%m%d_%H%M%S').json"
  tmp="$(mktemp)"
  echo '[]' > "$tmp"
  while read -r name; do
    [[ -z "$name" ]] && continue
    resp="$(list_records_by_name "$profile_json" "$name")" || { rm -f "$tmp"; return 1; }
    records="$(echo "$resp" | jq '.result')"
    jq --argjson add "$records" '. + $add' "$tmp" > "${tmp}.new"
    mv "${tmp}.new" "$tmp"
  done < <(echo "$names_json" | jq -r '.[]')
  jq -n --arg app "$APP_NAME" --arg version "$APP_VERSION" --arg task_id "$task_id" --arg created_at "$(date '+%Y-%m-%d %H:%M:%S %z')" --slurpfile records "$tmp" \
    '{app:$app,version:$version,task_id:$task_id,created_at:$created_at,records:$records[0]}' > "$backup_file"
  chmod 600 "$backup_file" 2>/dev/null || true
  rm -f "$tmp"
  log_msg "INFO" "已备份任务 ${task_id} 修改前 DNS 状态：${backup_file}"
}

update_or_create_cname() {
  local profile_json="$1"
  local task_json="$2"
  local full_name="$3"
  local target="$4"
  local zone_id token auto_create ttl proxied resp total cname_count record id current old_ttl old_proxied payload
  zone_id="$(profile_field "$profile_json" zone_id)"
  token="$(profile_field "$profile_json" api_token)"
  auto_create="$(echo "$task_json" | jq -r '.auto_create // true')"
  ttl="$(echo "$task_json" | jq -r '.ttl // 1')"
  proxied="$(echo "$task_json" | jq -r '.proxied // false')"

  resp="$(list_records_by_name "$profile_json" "$full_name")" || return 1
  total="$(echo "$resp" | jq '.result | length')"
  cname_count="$(echo "$resp" | jq '[.result[] | select(.type == "CNAME")] | length')"

  if [[ "$total" -gt "$cname_count" ]]; then
    say_error "${full_name} 存在非 CNAME 同名记录。为避免误删，已跳过。"
    echo "$resp" | jq -r '.result[] | "type=\(.type) name=\(.name) content=\(.content) id=\(.id)"' | while read -r line; do log_msg "ERROR" "$line"; done
    return 1
  fi
  if [[ "$cname_count" -gt 1 ]]; then
    say_error "${full_name} 存在多个 CNAME，同名记录异常，已跳过。"
    return 1
  fi

  if [[ "$cname_count" -eq 0 ]]; then
    if [[ "$auto_create" != "true" ]]; then
      say_error "${full_name} 不存在，且任务未启用自动创建。"
      return 1
    fi
    payload="$(jq -n --arg name "$full_name" --arg content "$target" --argjson ttl "$ttl" --argjson proxied "$proxied" '{type:"CNAME",name:$name,content:$content,ttl:$ttl,proxied:$proxied}')"
    cf_api "$token" POST "/zones/${zone_id}/dns_records" "$payload" >/dev/null || return 1
    say_info "已创建：${full_name} -> ${target}"
    return 0
  fi

  record="$(echo "$resp" | jq -c '.result[] | select(.type == "CNAME")')"
  id="$(echo "$record" | jq -r '.id')"
  current="$(echo "$record" | jq -r '.content' | sed 's/[.]$//')"
  old_ttl="$(echo "$record" | jq -r '.ttl // 1')"
  old_proxied="$(echo "$record" | jq -r '.proxied // false')"
  target="$(echo "$target" | sed 's/[.]$//')"
  if [[ "$current" == "$target" ]]; then
    log_msg "INFO" "无需更新：${full_name} 已指向 ${target}"
    return 0
  fi
  payload="$(jq -n --arg name "$full_name" --arg content "$target" --argjson ttl "$old_ttl" --argjson proxied "$old_proxied" '{type:"CNAME",name:$name,content:$content,ttl:$ttl,proxied:$proxied}')"
  cf_api "$token" PATCH "/zones/${zone_id}/dns_records/${id}" "$payload" >/dev/null || return 1
  say_info "已更新：${full_name} ${current} -> ${target}"
}

apply_task() {
  local task_id="$1"
  local force="${2:-normal}"
  local task profile_id profile schedule hash state_file last_hash zone names_json
  task="$(json_get_task "$task_id")"
  [[ -z "$task" ]] && { say_error "任务不存在：$task_id"; return 1; }
  if [[ "$(echo "$task" | jq -r '.enabled')" != "true" && "$force" != "force" ]]; then
    log_msg "INFO" "任务已停用，跳过：$task_id"
    return 0
  fi
  profile_id="$(echo "$task" | jq -r '.profile_id')"
  profile="$(json_get_profile "$profile_id")"
  [[ -z "$profile" ]] && { say_error "任务 ${task_id} 引用的域名配置不存在：${profile_id}"; return 1; }
  schedule="$(schedule_key_for_now "$task")"
  [[ -z "$schedule" ]] && { say_error "任务 ${task_id} 没有可用时间表。"; return 1; }
  hash="$(desired_hash "$schedule")"
  state_file="${STATE_DIR}/${task_id}.state"
  last_hash="$(cat "$state_file" 2>/dev/null || true)"
  if [[ "$force" != "force" && "$hash" == "$last_hash" ]]; then
    log_msg "INFO" "任务 ${task_id} 当前时间窗口已执行过，跳过。"
    return 0
  fi

  zone="$(echo "$profile" | jq -r '.zone_name')"
  names_json="$(echo "$schedule" | jq --arg zone "$zone" '[.records[].name | if . == "@" or . == $zone then $zone elif endswith("." + $zone) then . else . + "." + $zone end] | unique')"
  backup_records_before_apply "$task_id" "$profile" "$names_json" || return 1

  local failed=0
  while IFS=$'\t' read -r rname target; do
    [[ -z "$rname" ]] && continue
    local full_name
    full_name="$(fqdn_record_name "$zone" "$rname")"
    update_or_create_cname "$profile" "$task" "$full_name" "$target" || failed=1
  done < <(echo "$schedule" | jq -r '.records[] | [.name,.target] | @tsv')

  if [[ "$failed" -eq 0 ]]; then
    echo "$hash" > "$state_file"
    chmod 600 "$state_file" 2>/dev/null || true
    log_msg "INFO" "任务 ${task_id} 执行完成，时间点：$(echo "$schedule" | jq -r '.time')"
    return 0
  fi
  return 1
}

run_all_tasks() {
  require_config || return 1
  local force="${1:-normal}"
  local lock="/run/${APP_NAME}.lock"
  mkdir -p /run 2>/dev/null || true
  (
    flock -n 9 || { log_msg "WARN" "已有 cfcname 任务在运行，本次退出。"; exit 0; }
    local ids failed id
    ids="$(jq -r '.tasks[]?.id' "$CONFIG_FILE")"
    failed=0
    while read -r id; do
      [[ -z "$id" ]] && continue
      apply_task "$id" "$force" || failed=1
    done <<< "$ids"
    exit "$failed"
  ) 9>"$lock"
}

show_dns_status() {
  require_config || return 1
  local tid task profile_id profile zone schedule
  tid="$(select_task_id)" || return 1
  task="$(json_get_task "$tid")"
  profile_id="$(echo "$task" | jq -r '.profile_id')"
  profile="$(json_get_profile "$profile_id")"
  zone="$(echo "$profile" | jq -r '.zone_name')"
  schedule="$(schedule_key_for_now "$task")"
  line
  cecho "$C_BLUE" "任务当前应生效时间点：$(echo "$schedule" | jq -r '.time')"
  line
  while IFS=$'\t' read -r rname target; do
    local full_name resp
    full_name="$(fqdn_record_name "$zone" "$rname")"
    resp="$(list_records_by_name "$profile" "$full_name")" || continue
    echo "$resp" | jq -r --arg expected "$target" '.result[]? | "\(.type) \(.name) -> \(.content)  expected=" + $expected + "  ttl=\(.ttl) proxied=\(.proxied)"'
  done < <(echo "$schedule" | jq -r '.records[] | [.name,.target] | @tsv')
}


manual_modify_cname() {
  require_config || return 1
  local pid profile zone name target full_name resp fake_task names_json
  pid="$(select_profile_id)" || return 1
  profile="$(json_get_profile "$pid")"
  zone="$(echo "$profile" | jq -r '.zone_name')"
  line
  cecho "$C_BLUE" "手动修改指定 CNAME"
  line
  echo "当前域名：$zone"
  name="$(read_required 'CNAME 名称，例如 x001 或 x001.example.com: ')"
  target="$(read_required '新的 CNAME 目标，例如 target.example.com: ')"
  target="$(echo "$target" | sed 's/[.]$//')"
  full_name="$(fqdn_record_name "$zone" "$name")"
  echo
  cecho "$C_YELLOW" "将要修改：${full_name} -> ${target}"
  echo "当前记录："
  resp="$(list_records_by_name "$profile" "$full_name")" || return 1
  if [[ "$(echo "$resp" | jq '.result | length')" -eq 0 ]]; then
    echo "  当前不存在同名记录。"
  else
    echo "$resp" | jq -r '.result[] | "  \(.type) \(.name) -> \(.content) ttl=\(.ttl) proxied=\(.proxied) id=\(.id)"'
  fi
  if ! confirm "确认修改/创建该 CNAME"; then return 0; fi
  names_json="$(jq -n --arg n "$full_name" '[$n]')"
  backup_records_before_apply "manual" "$profile" "$names_json" || return 1
  fake_task="$(jq -n --argjson ttl "$(jq -r '.settings.default_ttl // 1' "$CONFIG_FILE")" --argjson proxied "$(jq -r '.settings.default_proxied // false' "$CONFIG_FILE")" '{auto_create:true,ttl:$ttl,proxied:$proxied}')"
  update_or_create_cname "$profile" "$fake_task" "$full_name" "$target"
}

restore_backup_interactive() {
  local files count idx file profile_id profile records_count
  mapfile -t files < <(ls -1t "$BACKUP_DIR"/dns_*.json 2>/dev/null | head -n 20)
  count=${#files[@]}
  if [[ "$count" -eq 0 ]]; then say_warn "没有找到 DNS 备份。"; return 1; fi
  line
  cecho "$C_BLUE" "最近 DNS 备份"
  local i=1
  for file in "${files[@]}"; do
    echo "${i}) $(basename "$file")"
    i=$((i+1))
  done
  line
  read -r -p "选择要恢复的备份序号: " idx
  [[ "$idx" =~ ^[0-9]+$ ]] || { say_error "序号无效"; return 1; }
  file="${files[$((idx-1))]:-}"
  [[ -z "$file" ]] && { say_error "序号不存在"; return 1; }
  records_count="$(jq '[.records[]? | select(.type == "CNAME")] | length' "$file")"
  [[ "$records_count" -eq 0 ]] && { say_error "备份中没有 CNAME 记录。"; return 1; }
  profile_id="$(select_profile_id)" || return 1
  profile="$(json_get_profile "$profile_id")"
  if ! confirm "确认使用当前选择的域名配置恢复备份里的 ${records_count} 条 CNAME 目标？不会删除新增记录"; then return 0; fi
  jq -r '.records[]? | select(.type == "CNAME") | [.name,.content] | @tsv' "$file" | while IFS=$'\t' read -r name content; do
    local fake_task
    fake_task='{"auto_create":true,"ttl":1,"proxied":false}'
    update_or_create_cname "$profile" "$fake_task" "$name" "$content"
  done
  say_info "恢复完成。"
}

install_scheduler() {
  need_root
  ensure_dirs
  if command -v systemctl >/dev/null 2>&1 && [[ -d /run/systemd/system ]]; then
    cat > "$SYSTEMD_SERVICE" <<EOF
[Unit]
Description=cfcname Cloudflare CNAME timed switch runner
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
ExecStart=${BIN_FILE} run --quiet
EOF
    cat > "$SYSTEMD_TIMER" <<EOF
[Unit]
Description=Run cfcname every minute

[Timer]
OnBootSec=30s
OnUnitActiveSec=60s
AccuracySec=5s
Persistent=true

[Install]
WantedBy=timers.target
EOF
    systemctl daemon-reload
    systemctl enable --now "${APP_NAME}.timer" >/dev/null 2>&1 && say_info "已启用 systemd timer：${APP_NAME}.timer" || say_error "systemd timer 启用失败。"
    rm -f "$CRON_FILE" 2>/dev/null || true
  else
    cat > "$CRON_FILE" <<EOF
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
* * * * * root flock -n /run/${APP_NAME}.cron.lock ${BIN_FILE} run --quiet >/dev/null 2>&1
EOF
    chmod 644 "$CRON_FILE"
    if command -v systemctl >/dev/null 2>&1; then
      systemctl enable --now cron >/dev/null 2>&1 || systemctl enable --now crond >/dev/null 2>&1 || true
    else
      service cron start >/dev/null 2>&1 || service crond start >/dev/null 2>&1 || true
    fi
    say_info "已启用 cron 定时任务：$CRON_FILE"
  fi
}

scheduler_status() {
  line
  cecho "$C_BLUE" "定时器状态"
  line
  if command -v systemctl >/dev/null 2>&1 && systemctl list-unit-files 2>/dev/null | grep -q "^${APP_NAME}.timer"; then
    systemctl status "${APP_NAME}.timer" --no-pager || true
  elif [[ -f "$CRON_FILE" ]]; then
    echo "使用 cron：$CRON_FILE"
    cat "$CRON_FILE"
  else
    say_warn "未检测到定时器。"
  fi
}

remove_scheduler() {
  need_root
  if command -v systemctl >/dev/null 2>&1; then
    systemctl disable --now "${APP_NAME}.timer" >/dev/null 2>&1 || true
    rm -f "$SYSTEMD_SERVICE" "$SYSTEMD_TIMER"
    systemctl daemon-reload >/dev/null 2>&1 || true
  fi
  rm -f "$CRON_FILE"
  say_info "已移除定时器。"
}

self_check() {
  require_config || return 1
  line
  cecho "$C_BLUE" "自检"
  line
  local ok=0
  for cmd in curl jq flock date awk sed grep; do
    if command -v "$cmd" >/dev/null 2>&1; then echo "[OK] $cmd"; else echo "[MISS] $cmd"; ok=1; fi
  done
  [[ -f "$CONFIG_FILE" ]] && echo "[OK] 配置文件：$CONFIG_FILE" || { echo "[MISS] 配置文件"; ok=1; }
  jq empty "$CONFIG_FILE" >/dev/null 2>&1 && echo "[OK] JSON 格式" || { echo "[MISS] JSON 格式异常"; ok=1; }
  echo "profiles=$(jq '.profiles|length' "$CONFIG_FILE" 2>/dev/null || echo 0), tasks=$(jq '.tasks|length' "$CONFIG_FILE" 2>/dev/null || echo 0)"
  scheduler_status
  return "$ok"
}

view_logs() {
  mkdir -p "$LOG_DIR"
  touch "$LOG_FILE" 2>/dev/null || true
  line
  cecho "$C_BLUE" "日志：$LOG_FILE"
  line
  echo "1) 查看最近 80 行"
  echo "2) 实时查看日志"
  echo "0) 返回"
  read -r -p "请选择: " c
  case "$c" in
    1) tail -n 80 "$LOG_FILE" ;;
    2) echo "按 Ctrl+C 退出"; tail -f "$LOG_FILE" ;;
    *) return ;;
  esac
}

edit_raw_config() {
  require_config || return 1
  local editor="${EDITOR:-vi}"
  cp -a "$CONFIG_FILE" "${BACKUP_DIR}/config_manual_$(date '+%Y%m%d_%H%M%S').json.bak"
  "$editor" "$CONFIG_FILE"
  if jq empty "$CONFIG_FILE" >/dev/null 2>&1; then
    chmod 600 "$CONFIG_FILE"
    say_info "配置 JSON 校验通过。"
  else
    say_error "配置 JSON 校验失败，请修复：$CONFIG_FILE"
    return 1
  fi
}

install_self() {
  need_root
  install_deps || return 1
  ensure_dirs
  local src
  src="$(readlink -f "$0" 2>/dev/null || echo "$0")"
  if [[ "$src" != "$BIN_FILE" ]]; then
    cp -f "$src" "$BIN_FILE"
    chmod 700 "$BIN_FILE"
    say_info "已安装命令：$BIN_FILE"
  else
    chmod 700 "$BIN_FILE"
    say_info "当前已经是安装路径：$BIN_FILE"
  fi
  init_empty_config
  install_scheduler
  say_info "安装完成。输入 cfcname 进入菜单。"
}

uninstall_self() {
  need_root
  line
  cecho "$C_RED" "卸载 cfcname"
  line
  echo "默认只删除命令和定时器，不删除配置、备份、日志。"
  if confirm "确认卸载命令和定时器"; then
    remove_scheduler
    rm -f "$BIN_FILE"
    say_info "已删除命令：$BIN_FILE"
  fi
  if confirm "是否同时删除配置、备份、日志？此操作不可恢复"; then
    rm -rf "$CONFIG_DIR" "$STATE_DIR" "$LOG_DIR"
    say_info "已删除配置、备份、日志。"
  fi
}

main_menu() {
  require_config || return 1
  while true; do
    clear
    line
    cecho "$C_CYAN" "        cfcname v${APP_VERSION} - Cloudflare CNAME 定时切换管理器"
    line
    echo "  1) 🚀 快速初始化向导"
    echo "  2) 🌐 域名 / API Token 配置管理"
    echo "  3) 🔁 CNAME 定时切换任务管理"
    echo "  4) ▶️  立即按当前时间同步全部任务"
    echo "  5) 🔨 强制校正全部任务（忽略上次执行状态）"
    echo "  6) 🔍 查看指定任务 DNS 状态"
    echo "  7) ✏️  手动修改指定 CNAME"
    echo "  8) 🕒 安装 / 修复定时器"
    echo "  9) 📌 查看定时器状态"
    echo " 10) 📜 查看日志"
    echo " 11) 🧪 自检"
    echo " 12) 🧯 从 DNS 备份恢复"
    echo " 13) 📝 手动编辑 JSON 配置"
    echo " 14) 🧹 卸载"
    echo "  0) 退出"
    line
    read -r -p "请选择: " c
    case "$c" in
      1) quick_init_wizard; pause ;;
      2) profiles_menu ;;
      3) tasks_menu ;;
      4) run_all_tasks normal; pause ;;
      5) run_all_tasks force; pause ;;
      6) show_dns_status; pause ;;
      7) manual_modify_cname; pause ;;
      8) install_scheduler; pause ;;
      9) scheduler_status; pause ;;
      10) view_logs; pause ;;
      11) self_check; pause ;;
      12) restore_backup_interactive; pause ;;
      13) edit_raw_config; pause ;;
      14) uninstall_self; pause ;;
      0) exit 0 ;;
      *) say_warn "无效选项"; pause ;;
    esac
  done
}

usage() {
  cat <<EOF
cfcname v${APP_VERSION}

用法：
  cfcname                 打开菜单
  cfcname install         安装/修复命令、依赖和定时器
  cfcname init            快速初始化向导
  cfcname run             定时器调用：按当前时间同步全部任务
  cfcname force-run       强制校正全部任务
  cfcname status          自检 + 定时器状态
  cfcname logs            查看日志菜单
  cfcname uninstall       卸载
  cfcname help            帮助

配置文件：${CONFIG_FILE}
日志文件：${LOG_FILE}
备份目录：${BACKUP_DIR}
EOF
}

main() {
  local cmd="${1:-menu}"
  case "$cmd" in
    help|-h|--help) usage; exit 0 ;;
  esac

  # 配置文件、日志、备份和定时器都位于 /etc、/var、/usr/local/bin，统一要求 root 执行，避免半写入状态。
  need_root

  case "$cmd" in
    install) install_self ;;
    init) quick_init_wizard ;;
    menu) main_menu ;;
    run) shift || true; run_all_tasks normal ;;
    force-run) run_all_tasks force ;;
    status) self_check ;;
    logs) view_logs ;;
    uninstall) uninstall_self ;;
    *) usage; exit 1 ;;
  esac
}

main "$@"
